# Model setup
RAVE.sample_rate: 44100

# Discriminator
Discriminator.sample_rate: 44100
Discriminator.rates: []
Discriminator.periods: [2, 3, 5, 7, 11]
Discriminator.fft_sizes: [2048, 1024, 512]
Discriminator.bands:
  - [0.0, 0.1]
  - [0.1, 0.25]
  - [0.25, 0.5]
  - [0.5, 0.75]
  - [0.75, 1.0]

# Optimization
AdamW_G.betas: [0.8, 0.99]
AdamW_G.lr: 0.0001

AdamW_D.betas: [0.8, 0.99]
AdamW_D.lr: 0.0001

ExponentialLR.gamma: 0.999996

amp: false
val_batch_size: 100 #overwritten in gpu yml
device: cuda
num_iters: 850000
save_iters: [10000, 50000, 100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000]
valid_freq: 10000
sample_freq: 10000
num_workers: 32 #overwritten in gpu yml
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]
seed: 0
lambdas:
  mel/loss: 15.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  multiband/loss: 5.0

VolumeNorm.db: [const, -16]

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.0
build_transform.augment:
  - Identity
build_transform.postprocess:
  - VolumeNorm
  - RescaleAudio
  - ShiftPhase

# Loss setup
MultiScaleSTFTLoss.window_lengths: [512]
MelSpectrogramLoss.n_mels: [5, 10, 20, 40, 80, 160, 320]
MelSpectrogramLoss.window_lengths: [32, 64, 128, 256, 512, 1024, 2048]
MelSpectrogramLoss.mel_fmin: [0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLoss.mel_fmax: [null, null, null, null, null, null, null]
MelSpectrogramLoss.pow: 1.0
MelSpectrogramLoss.clamp_eps: 1.0e-5
MelSpectrogramLoss.mag_weight: 0.0

# Data
batch_size: 2 #overwritten in gpu yml

train/AudioDataset.n_examples: 10000000
train/build_dataset.duration: 0.3715193
train/build_dataset.folders:
  music_hq:
    - ../vctk-small

val/build_transform.augment_prob: 1.0
val/AudioDataset.n_examples: 100
val/build_dataset.duration: 0.3715193
val/build_dataset.folders:
  music_hq:
    - ../valid-vctk

test/build_transform.augment_prob: 1.0
test/AudioDataset.n_examples: 100
test/build_dataset.duration: 0.3715193
test/build_dataset.folders:
  music_hq:
    - ../test-vctk

AudioLoader.shuffle: true
AudioDataset.without_replacement: true
